### ISSUE TITLE
Android crash on ApphudSdk.purchase

### ISSUE THREAD

**Issue by Artem2001Sd** [apphud/ApphudSDK-React-Native#61]
Calling `ApphudSdk.purchase(...) `and get crash on android. iOS works correctly 

`    "@apphud/react-native-apphud-sdk": "^2.0.0",`

`    "react-native": "0.67.1",
`

build.gradle config

```    ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 26
        compileSdkVersion = 33
        targetSdkVersion = 33
        ndkVersion = "21.4.7075529"
        ext {
            kotlin_version = '1.7.10'
        }
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:4.2.2")
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        classpath 'com.google.gms:google-services:4.3.10'


        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
```

```
FATAL EXCEPTION: mqt_native_modules

com.facebook.react.bridge.NoSuchKeyException: isConsumable

FATAL EXCEPTION: mqt_native_modules
Process: com.naturesoundsapp, PID: 17866
com.facebook.react.bridge.NoSuchKeyException: isConsumable
	at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:110)
	at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:114)
	at com.facebook.react.bridge.ReadableNativeMap.getBoolean(ReadableNativeMap.java:146)
	at com.reactnativeapphudsdk.ApphudSdkModule.purchase(ApphudSdkModule.kt:99)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loop(Looper.java:223)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
	at java.lang.Thread.run(Thread.java:923)

```

**Comment by ren6** [comment]
@Artem2001Sd we apologize for your issue. To avoid the crash, please always add `isConsumable` parameter to ApphudPurchaseProps interface, it will be ignored if it's not needed. We will make this parameter optional on Android in future releases.
Thank you!
